package models

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type UserModelDB struct {
	Id            uuid.UUID     `db:"id" json:"id"`
	Email         string        `db:"email" json:"email"`
	EmailVerified bool          `db:"email_verified" json:"email_verified"`
	PasswordHash  SQLNullString `db:"password_hash" json:"-"`

	FirstName SQLNullString `db:"first_name" json:"first_name"`
	LastName  SQLNullString `db:"last_name" json:"last_name"`
	Handle    SQLNullString `db:"handle" json:"handle"`
	FullName  string        `db:"full_name" json:"full_name"` // generated by the DB
	Initials  string        `db:"initials" json:"initials"`   // generated by the DB
	AvatarUrl SQLNullString `db:"avatar_url" json:"avatar_url"`
	Active    bool          `db:"active" json:"active"`

	GithubId     SQLNullString `db:"github_id" json:"github_id"`
	GithubEmail  SQLNullString `db:"github_email" json:"github_email"`
	GithubHandle SQLNullString `db:"github_handle" json:"github_handle"`
	GithubUrl    SQLNullString `db:"github_url" json:"github_url"`

	GoogleId    SQLNullString `db:"google_id" json:"google_id"`
	GoogleEmail SQLNullString `db:"google_email" json:"google_email"`

	FacebookId    SQLNullString `db:"facebook_id" json:"facebook_id"`
	FacebookEmail SQLNullString `db:"facebook_email" json:"facebook_email"`
	FacebookUrl   SQLNullString `db:"facebook_url" json:"-"`

	SpotifyId    SQLNullString `db:"spotify_id" json:"spotify_id"`
	SpotifyEmail SQLNullString `db:"spotify_email" json:"spotify_email"`
	SpotifyUrl   SQLNullString `db:"spotify_url" json:"-"`

	LastLoginAt sql.NullTime `db:"last_login_at" json:"-"`

	CreatedAt time.Time `db:"created_at" json:"-"`
	UpdatedAt time.Time `db:"updated_at" json:"-"`
}
