package models

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type UsersModelDB struct {
	Id            uuid.UUID     `db:"id" json:"id"`
	Email         string        `db:"email" json:"email"`
	EmailVerified bool          `db:"email_verified" json:"email_verified"`
	PasswordHash  SQLNullString `db:"password_hash" json:"-"`

	FirstName    SQLNullString `db:"first_name" json:"first_name"`
	LastName     SQLNullString `db:"last_name" json:"last_name"`
	Handle       SQLNullString `db:"handle" json:"handle"`
	UserFullName SQLNullString `db:"user_full_name" json:"user_full_name"` // generated by the DB
	AvatarUrl    SQLNullString `db:"avatar_url" json:"avatar_url"`
	Active       bool          `db:"active" json:"active"`

	GithubId     SQLNullString `db:"github_id" json:"-"`
	GithubHandle SQLNullString `db:"github_handle" json:"github_handle"`
	GithubUrl    SQLNullString `db:"github_url" json:"github_url"`

	GoogleId SQLNullString `db:"google_id" json:"-"`

	FacebookId  SQLNullString `db:"facebook_id" json:"-"`
	FacebookUrl SQLNullString `db:"facebook_url" json:"-"`

	SpotifyId  SQLNullString `db:"spotify_id" json:"-"`
	SpotifyUrl SQLNullString `db:"spotify_url" json:"-"`

	LastLoginAt sql.NullTime `db:"last_login_at" json:"last_login_at"`

	CreatedAt time.Time `db:"created_at" json:"created_at"`
	UpdatedAt time.Time `db:"updated_at" json:"updated_at"`
}
